stages:
  - build
  - distribute

yarn:
  stage: build
  image: node:lts-alpine3.14
  tags:
    # The shell Gitlab runner has to be used for this
    - docker
    - amd64

  script:
    # Install GIT and the submodules
    - apk update
    - apk add git
    - apk add curl
    - apk add xz
    - apk add build-base
    - git submodule init
    - git submodule update
    # Install all dependencies
    - yarn install
    # Build the distribtion
    - yarn build
    # Compress the distribution in the artefact file
    - tar cf seacat-admin-webui.tar dist
    - lzma -9 -e -T 0 seacat-admin-webui.tar

  artifacts:
    paths:
      - seacat-admin-webui.tar.lzma

azure main:
  stage: distribute
  image: mcr.microsoft.com/azure-cli

  tags:
    - docker
    - amd64

  dependencies:
    - yarn

  only:
    - main

  script:
    - az storage blob upload --overwrite --file seacat-admin-webui.tar.lzma --container-name "\$web" --name "seacat/master/seacat-admin-webui.tar.lzma" --connection-string "$AZURE_STORAGE_CONNECTION_STRING"


azure tags:
  stage: distribute
  image: mcr.microsoft.com/azure-cli

  tags:
    - docker
    - amd64

  dependencies:
    - yarn

  only:
    - tags

  script:
    - az storage blob upload --overwrite --file seacat-admin-webui.tar.lzma --container-name "\$web" --name "seacat/${CI_COMMIT_TAG}/seacat-admin-webui.tar.lzma" --connection-string "$AZURE_STORAGE_CONNECTION_STRING"
